# Generated by Django 3.1.1 on 2020-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200916_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meaning',
            name='exemple',
        ),
        migrations.AddField(
            model_name='meaning',
            name='tralata',
            field=models.CharField(default='r', max_length=20),
        ),
    ]
