# Generated by Django 3.1.1 on 2020-09-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='name',
            field=models.CharField(default='ss', max_length=60),
            preserve_default=False,
        ),
    ]
