# Generated by Django 3.1.1 on 2020-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200916_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='grammatical_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Verbe'), (1, 'Adjectif'), (2, 'Nom'), (3, 'Adverbe')], default=2),
        ),
    ]
