# Generated by Django 3.1.1 on 2020-09-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200916_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meaning',
            old_name='sentence',
            new_name='meaning',
        ),
    ]
