# Generated by Django 3.1.1 on 2020-09-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200916_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='exemple',
            field=models.ManyToManyField(blank=True, to='api.Exemple'),
        ),
    ]
