# Generated by Django 3.1.1 on 2020-09-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200916_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='word',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.word'),
        ),
    ]
