# Generated by Django 3.1.1 on 2020-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_code_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='use',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
